version: "3"

services:
  gateway:
    restart: always
    build: ./gateway/
    command: npm start
    volumes:
      - ./proto:/usr/src/proto
    ports:
      - "3001:3001"
    networks:
      - client-tier
      - server-tier
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes: 
      - ./data/db:/data/db
    ports: 
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks: 
      - server-tier
  user-service:
    restart: always
    build: ./user-service/
    command: npm run run
    volumes:
      - ./proto:/usr/src/proto
    ports: 
      - 50051:50051
    networks:
      - server-tier
networks:
  client-tier:
  server-tier:
    external: true